### ISSUE TITLE
Doesn't work with iOS

### ISSUE THREAD

**Issue by Lelehel** [Lord448/ArduinoESP32_BLE_as_UART#1]
Hi,

I had high hopes when I found this code. I was searching for a working ESP32 BLE solution for using with iOS. Your code compiled OK but the damn iPhone can't see the ESP's BLE characteristics.

Can you advice any solution or code modification if I want to use ESP32 BLE connected to a U-Blox F9P GNSS board? I would like to use SW maps on iOS.

Thanks in advance

**Comment by Lord448** [comment]
Hello Lelehel, i'm glad that you wanted to use my code, but unfortunately i don't have an IOS device in order to test the code and the connection beetwen BLE devices, however I saw some comments on Apple forums that talk about that problems, but they didn't talk about a solution, so I recommend you to buy some Android phone, because the operative system is more accesible than IOS. This is so useful when you're a developer and even more if you work on embedded software. Good Luck! and feel free to ask me for some help if you need it.
